server:
  port: 8080

spring:
  application:
    name: doc-layout-parser

  datasource:
    url: jdbc:postgresql://localhost:5432/doclayout_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

app:
  ocr:
    provider: ${OCR_PROVIDER:YANDEX}
    tessdata-path: "src/main/resources/tessdata"
    language: "rus"
    pageSegMode: 6
    paddle-url: ${SURYA_SERVICE_URL:http://localhost:5000/recognize}
    yandex:
      iam-token: ${YANDEX_OCR_IAM_TOKEN:}
      api-key: ${YANDEX_OCR_API_KEY:}
      folder-id: ${YANDEX_FOLDER_ID:}

  llm:
    enabled: ${USE_LLM_POST_PROCESSING:false}
    api-key: ${YANDEX_LLM_API_KEY:}
    model-id: ${YANDEX_LLM_PROMPT_ID:}

  image:
    target-width: 2000